/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateProjectInput = {
  id?: string | null,
  name: string,
};

export type ModelProjectConditionInput = {
  name?: ModelStringInput | null,
  and?: Array< ModelProjectConditionInput | null > | null,
  or?: Array< ModelProjectConditionInput | null > | null,
  not?: ModelProjectConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export enum PostStatus {
  OPEN = "OPEN",
  PENDING = "PENDING",
  RESOLVED = "RESOLVED",
}


export enum PostTag {
  BLOCKER = "BLOCKER",
  DESIGN = "DESIGN",
}


export type CreatePostInput = {
  id?: string | null,
  title: string,
  imageId: string,
  projectId: string,
  text: string,
  createdAt?: string | null,
  updatedAt?: string | null,
  status: PostStatus,
  tags: Array< PostTag | null >,
  attachments?: Array< string | null > | null,
};

export type ModelPostConditionInput = {
  title?: ModelStringInput | null,
  imageId?: ModelIDInput | null,
  projectId?: ModelIDInput | null,
  text?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  status?: ModelPostStatusInput | null,
  tags?: ModelPostTagListInput | null,
  attachments?: ModelIDInput | null,
  and?: Array< ModelPostConditionInput | null > | null,
  or?: Array< ModelPostConditionInput | null > | null,
  not?: ModelPostConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelPostStatusInput = {
  eq?: PostStatus | null,
  ne?: PostStatus | null,
};

export type ModelPostTagListInput = {
  eq?: Array< PostTag | null > | null,
  ne?: Array< PostTag | null > | null,
  contains?: PostTag | null,
  notContains?: PostTag | null,
};

export type UpdatePostInput = {
  id: string,
  title?: string | null,
  imageId?: string | null,
  projectId?: string | null,
  text?: string | null,
  createdAt?: string | null,
  updatedAt?: string | null,
  status?: PostStatus | null,
  tags?: Array< PostTag | null > | null,
  attachments?: Array< string | null > | null,
};

export type DeletePostInput = {
  id?: string | null,
};

export type CreateCommentInput = {
  id?: string | null,
  author: string,
  authorAvatar: string,
  annotation?: AnnotationInput | null,
  content: string,
  parentComment?: string | null,
  commentPostId: string,
};

export type AnnotationInput = {
  geometry: GeometryInput,
  data: AnnotationDataInput,
};

export type GeometryInput = {
  x: number,
  y: number,
  height: number,
  width: number,
  type: string,
};

export type AnnotationDataInput = {
  text: string,
  id: string,
};

export type ModelCommentConditionInput = {
  author?: ModelStringInput | null,
  authorAvatar?: ModelIDInput | null,
  content?: ModelStringInput | null,
  parentComment?: ModelIDInput | null,
  and?: Array< ModelCommentConditionInput | null > | null,
  or?: Array< ModelCommentConditionInput | null > | null,
  not?: ModelCommentConditionInput | null,
};

export type UpdateCommentInput = {
  id: string,
  author?: string | null,
  authorAvatar?: string | null,
  annotation?: AnnotationInput | null,
  content?: string | null,
  parentComment?: string | null,
  commentPostId?: string | null,
};

export type DeleteCommentInput = {
  id?: string | null,
};

export type ModelProjectFilterInput = {
  id?: ModelIDInput | null,
  name?: ModelStringInput | null,
  and?: Array< ModelProjectFilterInput | null > | null,
  or?: Array< ModelProjectFilterInput | null > | null,
  not?: ModelProjectFilterInput | null,
};

export type ModelPostFilterInput = {
  id?: ModelIDInput | null,
  title?: ModelStringInput | null,
  imageId?: ModelIDInput | null,
  projectId?: ModelIDInput | null,
  text?: ModelStringInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  status?: ModelPostStatusInput | null,
  tags?: ModelPostTagListInput | null,
  attachments?: ModelIDInput | null,
  and?: Array< ModelPostFilterInput | null > | null,
  or?: Array< ModelPostFilterInput | null > | null,
  not?: ModelPostFilterInput | null,
};

export type ModelCommentFilterInput = {
  id?: ModelIDInput | null,
  author?: ModelStringInput | null,
  authorAvatar?: ModelIDInput | null,
  content?: ModelStringInput | null,
  parentComment?: ModelIDInput | null,
  and?: Array< ModelCommentFilterInput | null > | null,
  or?: Array< ModelCommentFilterInput | null > | null,
  not?: ModelCommentFilterInput | null,
};

export type CreateProjectMutationVariables = {
  input: CreateProjectInput,
  condition?: ModelProjectConditionInput | null,
};

export type CreateProjectMutation = {
  createProject:  {
    __typename: "Project",
    id: string,
    name: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type CreatePostMutationVariables = {
  input: CreatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type CreatePostMutation = {
  createPost:  {
    __typename: "Post",
    id: string,
    title: string,
    imageId: string,
    projectId: string,
    text: string,
    createdAt: string | null,
    updatedAt: string | null,
    status: PostStatus,
    tags: Array< PostTag | null >,
    attachments: Array< string | null > | null,
    comments:  {
      __typename: "ModelCommentConnection",
      items:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type UpdatePostMutationVariables = {
  input: UpdatePostInput,
  condition?: ModelPostConditionInput | null,
};

export type UpdatePostMutation = {
  updatePost:  {
    __typename: "Post",
    id: string,
    title: string,
    imageId: string,
    projectId: string,
    text: string,
    createdAt: string | null,
    updatedAt: string | null,
    status: PostStatus,
    tags: Array< PostTag | null >,
    attachments: Array< string | null > | null,
    comments:  {
      __typename: "ModelCommentConnection",
      items:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type DeletePostMutationVariables = {
  input: DeletePostInput,
  condition?: ModelPostConditionInput | null,
};

export type DeletePostMutation = {
  deletePost:  {
    __typename: "Post",
    id: string,
    title: string,
    imageId: string,
    projectId: string,
    text: string,
    createdAt: string | null,
    updatedAt: string | null,
    status: PostStatus,
    tags: Array< PostTag | null >,
    attachments: Array< string | null > | null,
    comments:  {
      __typename: "ModelCommentConnection",
      items:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type CreateCommentMutationVariables = {
  input: CreateCommentInput,
  condition?: ModelCommentConditionInput | null,
};

export type CreateCommentMutation = {
  createComment:  {
    __typename: "Comment",
    id: string,
    author: string,
    authorAvatar: string,
    annotation:  {
      __typename: "Annotation",
      geometry:  {
        __typename: "Geometry",
        x: number,
        y: number,
        height: number,
        width: number,
        type: string,
      },
      data:  {
        __typename: "AnnotationData",
        text: string,
        id: string,
      },
    } | null,
    content: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    },
    parentComment: string | null,
    subComments:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type UpdateCommentMutationVariables = {
  input: UpdateCommentInput,
  condition?: ModelCommentConditionInput | null,
};

export type UpdateCommentMutation = {
  updateComment:  {
    __typename: "Comment",
    id: string,
    author: string,
    authorAvatar: string,
    annotation:  {
      __typename: "Annotation",
      geometry:  {
        __typename: "Geometry",
        x: number,
        y: number,
        height: number,
        width: number,
        type: string,
      },
      data:  {
        __typename: "AnnotationData",
        text: string,
        id: string,
      },
    } | null,
    content: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    },
    parentComment: string | null,
    subComments:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type DeleteCommentMutationVariables = {
  input: DeleteCommentInput,
  condition?: ModelCommentConditionInput | null,
};

export type DeleteCommentMutation = {
  deleteComment:  {
    __typename: "Comment",
    id: string,
    author: string,
    authorAvatar: string,
    annotation:  {
      __typename: "Annotation",
      geometry:  {
        __typename: "Geometry",
        x: number,
        y: number,
        height: number,
        width: number,
        type: string,
      },
      data:  {
        __typename: "AnnotationData",
        text: string,
        id: string,
      },
    } | null,
    content: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    },
    parentComment: string | null,
    subComments:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type GetPostQueryVariables = {
  id: string,
};

export type GetPostQuery = {
  getPost:  {
    __typename: "Post",
    id: string,
    title: string,
    imageId: string,
    projectId: string,
    text: string,
    createdAt: string | null,
    updatedAt: string | null,
    status: PostStatus,
    tags: Array< PostTag | null >,
    attachments: Array< string | null > | null,
    comments:  {
      __typename: "ModelCommentConnection",
      items:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type GetProjectQueryVariables = {
  id: string,
};

export type GetProjectQuery = {
  getProject:  {
    __typename: "Project",
    id: string,
    name: string,
    posts:  {
      __typename: "ModelPostConnection",
      items:  Array< {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type ListProjectsQueryVariables = {
  filter?: ModelProjectFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListProjectsQuery = {
  listProjects:  {
    __typename: "ModelProjectConnection",
    items:  Array< {
      __typename: "Project",
      id: string,
      name: string,
      posts:  {
        __typename: "ModelPostConnection",
        items:  Array< {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type ListPostsQueryVariables = {
  filter?: ModelPostFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPostsQuery = {
  listPosts:  {
    __typename: "ModelPostConnection",
    items:  Array< {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetCommentQueryVariables = {
  id: string,
};

export type GetCommentQuery = {
  getComment:  {
    __typename: "Comment",
    id: string,
    author: string,
    authorAvatar: string,
    annotation:  {
      __typename: "Annotation",
      geometry:  {
        __typename: "Geometry",
        x: number,
        y: number,
        height: number,
        width: number,
        type: string,
      },
      data:  {
        __typename: "AnnotationData",
        text: string,
        id: string,
      },
    } | null,
    content: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    },
    parentComment: string | null,
    subComments:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type ListCommentsQueryVariables = {
  filter?: ModelCommentFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCommentsQuery = {
  listComments:  {
    __typename: "ModelCommentConnection",
    items:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type OnCreatePostSubscription = {
  onCreatePost:  {
    __typename: "Post",
    id: string,
    title: string,
    imageId: string,
    projectId: string,
    text: string,
    createdAt: string | null,
    updatedAt: string | null,
    status: PostStatus,
    tags: Array< PostTag | null >,
    attachments: Array< string | null > | null,
    comments:  {
      __typename: "ModelCommentConnection",
      items:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type OnUpdatePostSubscription = {
  onUpdatePost:  {
    __typename: "Post",
    id: string,
    title: string,
    imageId: string,
    projectId: string,
    text: string,
    createdAt: string | null,
    updatedAt: string | null,
    status: PostStatus,
    tags: Array< PostTag | null >,
    attachments: Array< string | null > | null,
    comments:  {
      __typename: "ModelCommentConnection",
      items:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type OnDeletePostSubscription = {
  onDeletePost:  {
    __typename: "Post",
    id: string,
    title: string,
    imageId: string,
    projectId: string,
    text: string,
    createdAt: string | null,
    updatedAt: string | null,
    status: PostStatus,
    tags: Array< PostTag | null >,
    attachments: Array< string | null > | null,
    comments:  {
      __typename: "ModelCommentConnection",
      items:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
      nextToken: string | null,
    } | null,
  } | null,
};

export type OnCreateCommentSubscription = {
  onCreateComment:  {
    __typename: "Comment",
    id: string,
    author: string,
    authorAvatar: string,
    annotation:  {
      __typename: "Annotation",
      geometry:  {
        __typename: "Geometry",
        x: number,
        y: number,
        height: number,
        width: number,
        type: string,
      },
      data:  {
        __typename: "AnnotationData",
        text: string,
        id: string,
      },
    } | null,
    content: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    },
    parentComment: string | null,
    subComments:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type OnUpdateCommentSubscription = {
  onUpdateComment:  {
    __typename: "Comment",
    id: string,
    author: string,
    authorAvatar: string,
    annotation:  {
      __typename: "Annotation",
      geometry:  {
        __typename: "Geometry",
        x: number,
        y: number,
        height: number,
        width: number,
        type: string,
      },
      data:  {
        __typename: "AnnotationData",
        text: string,
        id: string,
      },
    } | null,
    content: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    },
    parentComment: string | null,
    subComments:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
  } | null,
};

export type OnDeleteCommentSubscription = {
  onDeleteComment:  {
    __typename: "Comment",
    id: string,
    author: string,
    authorAvatar: string,
    annotation:  {
      __typename: "Annotation",
      geometry:  {
        __typename: "Geometry",
        x: number,
        y: number,
        height: number,
        width: number,
        type: string,
      },
      data:  {
        __typename: "AnnotationData",
        text: string,
        id: string,
      },
    } | null,
    content: string,
    post:  {
      __typename: "Post",
      id: string,
      title: string,
      imageId: string,
      projectId: string,
      text: string,
      createdAt: string | null,
      updatedAt: string | null,
      status: PostStatus,
      tags: Array< PostTag | null >,
      attachments: Array< string | null > | null,
      comments:  {
        __typename: "ModelCommentConnection",
        items:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
        nextToken: string | null,
      } | null,
    },
    parentComment: string | null,
    subComments:  Array< {
      __typename: "Comment",
      id: string,
      author: string,
      authorAvatar: string,
      annotation:  {
        __typename: "Annotation",
        geometry:  {
          __typename: "Geometry",
          x: number,
          y: number,
          height: number,
          width: number,
          type: string,
        },
        data:  {
          __typename: "AnnotationData",
          text: string,
          id: string,
        },
      } | null,
      content: string,
      post:  {
        __typename: "Post",
        id: string,
        title: string,
        imageId: string,
        projectId: string,
        text: string,
        createdAt: string | null,
        updatedAt: string | null,
        status: PostStatus,
        tags: Array< PostTag | null >,
        attachments: Array< string | null > | null,
        comments:  {
          __typename: "ModelCommentConnection",
          items:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
          nextToken: string | null,
        } | null,
      },
      parentComment: string | null,
      subComments:  Array< {
        __typename: "Comment",
        id: string,
        author: string,
        authorAvatar: string,
        annotation:  {
          __typename: "Annotation",
          geometry:  {
            __typename: "Geometry",
            x: number,
            y: number,
            height: number,
            width: number,
            type: string,
          },
          data:  {
            __typename: "AnnotationData",
            text: string,
            id: string,
          },
        } | null,
        content: string,
        post:  {
          __typename: "Post",
          id: string,
          title: string,
          imageId: string,
          projectId: string,
          text: string,
          createdAt: string | null,
          updatedAt: string | null,
          status: PostStatus,
          tags: Array< PostTag | null >,
          attachments: Array< string | null > | null,
          comments:  {
            __typename: "ModelCommentConnection",
            nextToken: string | null,
          } | null,
        },
        parentComment: string | null,
        subComments:  Array< {
          __typename: "Comment",
          id: string,
          author: string,
          authorAvatar: string,
          content: string,
          post:  {
            __typename: "Post",
            id: string,
            title: string,
            imageId: string,
            projectId: string,
            text: string,
            createdAt: string | null,
            updatedAt: string | null,
            status: PostStatus,
            tags: Array< PostTag | null >,
            attachments: Array< string | null > | null,
          },
          parentComment: string | null,
          subComments:  Array< {
            __typename: "Comment",
            id: string,
            author: string,
            authorAvatar: string,
            content: string,
            parentComment: string | null,
          } | null > | null,
        } | null > | null,
      } | null > | null,
    } | null > | null,
  } | null,
};
